# Generated by Django 2.1 on 2018-09-06 02:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('79513c0f-124f-46a1-a379-38aa237459f7'), editable=False, primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('url_link', models.URLField(blank=True, null=True, verbose_name='link')),
                ('username', models.CharField(max_length=255, verbose_name='account_name')),
                ('password', models.CharField(max_length=255, verbose_name='account_password')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
