# Generated by Django 2.1 on 2018-08-29 07:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EndPoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('endpoint', models.CharField(max_length=200, verbose_name='endpoint')),
                ('description', models.CharField(blank=True, max_length=300, null=True, verbose_name='descrpition')),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id')),
                ('title', models.CharField(max_length=200, verbose_name='host')),
                ('login_endpoint', models.CharField(blank=True, max_length=200, null=True, verbose_name='login')),
                ('username', models.CharField(blank=True, max_length=200, null=True, verbose_name='login_user')),
                ('password', models.CharField(blank=True, max_length=200, null=True, verbose_name='login_password')),
                ('is_delete', models.BooleanField(default=False, verbose_name='delete')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
            ],
        ),
        migrations.AddField(
            model_name='endpoint',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapi.Host'),
        ),
    ]
