# Generated by Django 2.1 on 2018-08-30 08:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataBase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id')),
                ('title', models.CharField(max_length=200, unique=True, verbose_name='title')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('username', models.CharField(blank=True, max_length=200, null=True, verbose_name='user')),
                ('password', models.CharField(blank=True, max_length=200, null=True, verbose_name='password')),
                ('host', models.CharField(blank=True, max_length=200, null=True, verbose_name='host')),
                ('port', models.CharField(blank=True, max_length=200, null=True, verbose_name='port')),
                ('db', models.CharField(blank=True, max_length=200, null=True, verbose_name='db')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('web_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapi.Host')),
            ],
        ),
    ]
